### ISSUE TITLE
Build issues with current website

### ISSUE THREAD

**Issue by adrianmc** [recharts/recharts.org#10]
I found some bugs:

- [ ] Font icons are not being included.
  - The font icons rely on an SCSS file: `simple-line-icons/scss/simple-line-icons.scss`
  https://github.com/recharts/recharts.org/blob/master/src/views/IndexView.js#L7
  - The SCSS file references other font files within the `node_module` folder
- [ ] Script for Github Button not included in the build `index.html`.
  - Make sure the `index.html` that gets built includes the script:
    https://github.com/recharts/recharts.org/blob/master/index.html#L14

**Comment by xile611** [comment]
@adrianmc  Fixed. But the website may update after few hours.
