### ISSUE TITLE
Code windows in "Examples" section are too small.

### ISSUE THREAD

**Issue by mlaga97** [recharts/recharts.org#120]
The window that displays example code has a maximum size of 30 characters wide by 24 lines tall. This is very small, and too small to be very useful for anyone looking at the longer examples without having to copy and paste the code to an external text editor.

Screenshot of code window from "Examples" section:
![Selection_2020053016:29:42](https://user-images.githubusercontent.com/6457464/83339806-9feb1800-a296-11ea-8dda-81026e3b1121.png)

Using Chrome 81 on Ubuntu 18.04 on a 4K monitor with the default zoom level, the code window only was only capable of using about 1.33% of the total area inside the browser viewport.

One possible remedy would be to display the code under the example window, similar to the API example code windows (as shown below).

Screenshot of code window from "API" section for comparison:
![Selection_2020053017:00:58](https://user-images.githubusercontent.com/6457464/83339875-7f6f8d80-a297-11ea-86f3-ad9b4221ded6.png)

**Comment by Yilun-Sun** [comment]
Solved with #239 
Now your will get: 
![image](https://user-images.githubusercontent.com/43896664/215239243-00486c4f-ee54-49e3-ace3-0c8c34822fa2.png)
