### ISSUE TITLE
Some company icon links are outdated

### ISSUE THREAD

**Issue by dillonreedy** [recharts/recharts.org#152]
When navigating to the home page, in the list of users using Recharts, some of the company logo links are outdated:

![image](https://user-images.githubusercontent.com/3454995/103490578-7ffa7480-4de2-11eb-8c6c-856fe8487dee.png)

**Comment by SammyIsra** [comment]
Should this be re-addressed? One new company logo (yety) has broken since the PR that addressed this issue previously:
![image](https://user-images.githubusercontent.com/8962228/185218073-24622a33-dec5-4369-90a9-36bf7867df52.png)

**Comment by dillonreedy** [comment]
@arcthur could I gain merging permissions to allow people to contribute to this project?

It would free you up from being responsible for this.
