### ISSUE TITLE
Make Code Examples Responsive

### ISSUE THREAD

**Issue by dillonreedy** [recharts/recharts.org#154]
When navigating to any of the code examples, the code section is cut off and you have to use sideways scroll bars. Although there is plenty of real-estate to expand out into on my 1920x1080 monitor. It would be nice to have the code examples responsive.

![image](https://user-images.githubusercontent.com/3454995/103491104-7c68ec80-4de6-11eb-8927-f18e12ccfdfe.png)

**Comment by Yilun-Sun** [comment]
Solved #239
