### ISSUE TITLE
jsfiddle does not support React 15+

### ISSUE THREAD

**Issue by avindra** [recharts/recharts.org#156]
The examples hosted on jsfiddle have seen compiler problems, e.g.:

https://github.com/recharts/recharts/issues/2375

Also, it may be worthwhile to move all the code examples into a source repo belonging to recharts, in case those code boxes go offline. I recommend _not_ using storybook, but rather whatever tool can do this as simply as possible.

**Comment by avindra** [comment]
To clarify: the embedded examples as seen from the website are working fine.

It breaks when you go into the fullscreen sandbox and try to edit code.

Upstream: https://github.com/jsfiddle/jsfiddle-issues/issues/1670

**Comment by avindra** [comment]
After reviewing jsfiddle, it appears that the development has gone into maintenance-only mode. Note that the options include prototype, and that there is no support for React 15+:

![image](https://user-images.githubusercontent.com/126848/104648807-b2795c80-5681-11eb-9100-f077ec77c422.png)

**Comment by avindra** [comment]
Codesandbox is compatible with our Recharts 2.0: https://codesandbox.io/

Is anyone opposed to switching? (Some) amount of [the codesandebox code](https://github.com/codesandbox/) is open source, not sure how much complexity is involved in self-hosting it though.

**Comment by avindra** [comment]
Re: self-hosting

The backend is Phoenix and still private: 

https://github.com/codesandbox/codesandbox-client#other-codesandbox-repositories

So self-hosting is neither documented nor encouraged. Effectively, switching to codesandbox:

 * fixes jsfiddle sandbox being broken (working sandbox again)
 * does not solve the vendor-lock issue (no self-hosting)

**Comment by ckifer** [comment]
@avindra I think JSFiddle is still devving new features although slowly and those dependency choices are incredibly out of date. They've had a few posts recently on their [Twitter](https://twitter.com/jsfiddle?lang=en). 

Either way I think the move to CodeSandbox is a good one to make.

**Comment by pnewhook** [comment]
FYI, clicking on Run on the examples page fails
![image](https://user-images.githubusercontent.com/92876/106616523-a6bfde00-653b-11eb-8883-f1617f997e4b.png)

Simply updating the react version allowed the examples to run 
![image](https://user-images.githubusercontent.com/92876/106616928-16ce6400-653c-11eb-964a-c8296840de8a.png)

**Comment by xile611** [comment]
All the examples have been migrated to codesandbox
