### ISSUE TITLE
[Documentation] strokeDasharray is wrong in Line documentation

### ISSUE THREAD

**Issue by rdwoodring** [recharts/recharts.org#174]
The `strokeDasharray` prop in the [https://github.com/recharts/recharts.org/blob/master/src/docs/api/Line.js#L359](Line component documentation) is incorrect. It's listed as `strokeDashArray` but the actual prop appears to be `strokeDashArray`.

Expected
The documentation should match the actual prop

Actual
The casing of the prop in the documentation does not match the casing of the prop in the source code

**Comment by ckifer** [comment]
Hi @rdwoodring, thanks for the report. This is actually intended `strokeDasharray` is the correct property as per the React docs for SVGAttributes
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts#L2674
