### ISSUE TITLE
[Dev Server] Refresh page got error

### ISSUE THREAD

**Issue by Yilun-Sun** [recharts/recharts.org#218]
Problem
---
Clone recharts.org repo to local, start dev server at 127.0.0.1:4000.
Direct to http://127.0.0.1:4000/en-US/examples (or other locations), refresh page. 
Got a blank page with error: Cannot GET ***

Screenshot
---
![image](https://user-images.githubusercontent.com/43896664/206352848-386ad7e2-f7eb-40fc-bff2-91c24eaa5c4b.png)

**Comment by ckifer** [comment]
This is merged, closing
