### ISSUE TITLE
Better Code Runner

### ISSUE THREAD

**Issue by Yilun-Sun** [recharts/recharts.org#238]
There are many problems with the existing code runner:
- style: no responsive height / width
- have to write(show) a lot of irrelevant code 

other lib: 
![image](https://user-images.githubusercontent.com/43896664/211712164-0ca94753-5573-415d-8989-7e0738171432.png)

our: 
![image](https://user-images.githubusercontent.com/43896664/211712232-5bd51cd4-eb75-4d93-9790-d519c9f6a9ab.png)

The code runner could be replaced with a better one

For the quick fix of the current runner: #236 fixed #155 
Related issues: #154

**Comment by ckifer** [comment]
Deployed - looks good! Closed by #239
