### ISSUE TITLE
Site 404s on refresh

### ISSUE THREAD

**Issue by kjschiroo** [recharts/recharts.org#24]
You can navigate to http://recharts.org/en-US/examples by going to recharts.org, but if you click the link or refresh the page once you get there it 404s.

**Comment by xile611** [comment]
Fixed

**Comment by kjschiroo** [comment]
I'm still seeing 404s. Has this been deployed?

**Comment by xile611** [comment]
@kjschiroo We have changed the history of react-router from `brsowerHistory` to `hashHistory`. So the url has changed. Visit [http://recharts.org/#/en-US/examples](http://recharts.org/#/en-US/examples) instead.

**Comment by ppozniak** [comment]
Did you go back to browserHistory, as the problem occurs once again?
