### ISSUE TITLE
Images with img.alicdn.com URLs do not work in countries like India.

### ISSUE THREAD

**Issue by abhiram11** [recharts/recharts.org#256]
The `logoImgUrl` defined in the data in `src\docs\users\users.js` has a couple of images from `img.alicdn.com` which do not load in India. I would request you to check for alternatives, if required, based on how many countries have not allowed the same.

Thanks
![AliCDN issue](https://user-images.githubusercontent.com/20269286/218551443-10e6990c-6438-46fc-879a-d7dfff9d1ff0.JPG)

**Comment by nikolasrieble** [comment]
Good finding. The simplest thing one could do is simply download the images and add them as assets. 
Otherwise we could never be sure whether certain sources do not work in certain countries.

**Comment by abhiram11** [comment]
I will do it tomorrow 😄

**Comment by ckifer** [comment]
Had to copy the assets to the docs folder so they're accessible in GH pages but should be resolved now. Closing issue, thanks!
