### ISSUE TITLE
Automate builds

### ISSUE THREAD

**Issue by charpeni** [recharts/recharts.org#286]
Currently, [recharts.org](recharts.org) is published via GitHub pages and is using the `master` branch as both source and generated website.

It means that if we do land some changes but forget to run a build, then the website will be deployed with a previous build, even though the latest changes are included in the branch.

To mitigate this, we should be able to configure this repository to use another target branch to deploy to GitHub pages (e.g., `website`) and configure our CI to always build on merge and then commit the built website to this newly created branch.

Once upon a time, that's what we did for the React Native website and it worked great! Happy to set this up here.

Related to: https://github.com/recharts/recharts.org/pull/276, https://github.com/recharts/recharts.org/pull/285.

**Comment by charpeni** [comment]
Just realized they introduced a new way of building GitHub Pages:

<img width="279" alt="Screenshot 2023-11-21 at 10 08 04 AM" src="https://github.com/recharts/recharts.org/assets/7189823/de4bf0b1-8760-47d1-8c2a-646c9fb8250b">

We should be able to configure a workflow to build Jekyll and introduce our pre-build script so that we install dependencies, build our website, then build Jekyll. It means we wouldn't have to commit the generated website anymore and it will be done just in time.

**Comment by ckifer** [comment]
Been meaning to do this for a while, thanks for the initiative!

We are using the storybook more now, but this does still need to be addressed. If you'd like to take it, that'd be awesome. I can give permissions to do what is needed, could you outline the steps before I give those permissions? 
Just want to be clear on the changes, I haven't used Jekyll in a long while

**Comment by charpeni** [comment]
Sure thing!

I'm assuming we're currently deploying to GitHub Pages via `Deploy from a branch`, which is the Classic Pages experience. 

That's probably the reason why we have the following workflow showing up magically in GitHub Actions: https://github.com/recharts/recharts.org/actions/workflows/pages/pages-build-deployment. I said magically because we don't have any explicit workflow defined for it, so I assumed it is part of the Classic Pages experience.

I would like to switch from `Deploy from a branch` to `GitHub Actions` and configure an explicit workflow that will do exactly what we have currently in the workflow `pages-build-deployment` (keep Jekyll and everything else exactly like it is), but in the `build` job, add new steps between `Checkout` and `Build with Jekyll` to install npm dependencies and run `npm run build` before building Jekyll to make sure we're always building the website from a fresh build.

It also means we won't have to commit `/docs` anymore as it will always be done before deploying.

**Comment by ckifer** [comment]
Sounds good - Would you be able to the workflow test the workflow on a fork? 

since there is no pre-prod/staging environment we should be able to configure things to work on our forks so we don't accidentally mess with the current site. After we get that working I can give permissions and make the PR?

**Comment by charpeni** [comment]
Correct, I should be able to implement the workflow in my fork and even test deployments when merging on `master` within my fork before merging it here.

Do you mind confirming what's the actual configuration for GitHub Pages?

**Comment by ckifer** [comment]
yeah the setup is exactly as you said pretty much

<img width="849" alt="image" src="https://github.com/recharts/recharts.org/assets/25180830/9c68d82f-28b4-4f65-9f4b-2540011d8241">
