### ISSUE TITLE
ReferenceArea documentation does not mention shape prop

### ISSUE THREAD

**Issue by d4rky-pl** [recharts/recharts.org#34]
`ReferenceArea` allows easy replacement of `Rectangle` inside using `shape` prop. Unfortunately we only discovered this after two days of coding when we checked the source :sweat_smile:

I'd send a pull request but unfortunately I don't know Chinese :(

**Comment by xile611** [comment]
@d4rky-pl PR is welcome, you can only add English part. We'll add the translation of Chinese.

**Comment by kaizoku-kenshin** [comment]
@d4rky-pl  I need that `documentation` , can you put up a `jsfiddle`. I will raise a PR with a fix in the documentation once I understand that.

**Comment by kaizoku-kenshin** [comment]
So I was checking out  the code and found out that you can't use `shape` unless until you specify one of the `x1`,` x2`,`y1`,`y2`.  This is an actual bug in `ReferenceArea`.

**Comment by ckifer** [comment]
This looks resolved - closing this issue as completed
