### ISSUE TITLE
Tooltip and scatter plot

### ISSUE THREAD

**Issue by bettse** [recharts/recharts.org#45]
I noticed that the Tooltip is before the Scatterplot in the example code:
https://github.com/recharts/recharts.org/blob/master/src/docs/exampleComponents/ScatterChart/SimpleScatterChart.js

but after in the jsFiddle: http://jsfiddle.net/8ueLrpya/20/

and I noticed that when its after, the tooltip disappears even when the mouse is still over the point, which is frustrating.  I wanted to mention it in case maybe there was a bug, or perhaps it was just something to document.

**Comment by paulmelnikow** [comment]
Updated fiddle showing the problem: https://jsfiddle.net/alidingling/uLysj0u2/

PR with a fix: https://github.com/recharts/recharts/pull/1369
