### ISSUE TITLE
strokeWidth for Area

### ISSUE THREAD

**Issue by franciscop-invast** [recharts/recharts.org#55]
Add documentation for strokeWidth for the Area. Something like this would work:

***

## strokeWidth  `Number` _optional_

The width of the stroke for the plot lines in pixels. The higher the number, the thicker the line.

**DEFAULT**: false
**FORMAT**:

```js
<Area strokeWidth={1} />
<Area strokeWidth={2} />
<Area strokeWidth={5.3} />
```

**Comment by ckifer** [comment]
We have to balance what properties we put in the documentation. `Area` extends SVGProps https://github.com/recharts/recharts/blob/master/src/cartesian/Area.tsx#L86
which adds n attributes to accepted types from an SVG which might not have been the best decision. 

Stroke width however is certainly used so this is good to add to the docs
