### ISSUE TITLE
The size of charts container is adjusted over and over again

### ISSUE THREAD

**Issue by drubear** [recharts/recharts.org#6]
http://recharts.org/examples/#ComposedResponsiveContainer

The charts container is always shaking in my browser - Chrome Version 50.0.2652.0 (64-bit) for Mac OS X 10.11.12, and my colleagues also encountered this issue when they browsed that page in Chrome for Windows 10.

![1](https://cloud.githubusercontent.com/assets/1535544/14037318/1985c0bc-f27d-11e5-9e7b-0a6f4ed4be6b.gif)

**Comment by xile611** [comment]
It works normally in chrome 49.0.2623.87 (64-bit) and  51.0.2689.0 canary (64-bit).
Maybe it's the problem of Chrome Version 50.0.2652.0.
