### ISSUE TITLE
master branch has regressed

### ISSUE THREAD

**Issue by pojka** [recharts/recharts.org#69]
I noticed that the changes that were merged in https://github.com/recharts/recharts.org/pull/62 are no longer present, and that the file does not show the change in its history (https://github.com/recharts/recharts.org/blob/master/src/app.js)

Perhaps a bad merge, but It's odd... I can't see any commit after #62 was merged that reverts the file.

**Comment by ppozniak** [comment]
Came here to say that.

**Comment by dylmye** [comment]
This is making the website unusable for us, please prioritise this fix. Thanks
