### ISSUE TITLE
Could you enable enforce HTTPS?

### ISSUE THREAD

**Issue by ykzts** [recharts/recharts.org#70]
![Screenshot on settings of GitHub repository](https://user-images.githubusercontent.com/12539/42977660-6dfa6720-8c03-11e8-9265-070c8d0edfca.png)

https://github.com/recharts/recharts.org/settings

**Comment by ckifer** [comment]
Gonna +1 bump this because it really needs done

**Comment by ckifer** [comment]
This is done, resolving
