### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by fehergeri13** [recharts/recharts.org#74]
When I navigate to the api -> ResponsiveContainer link, and I refresh the page, I get a 404 error.

http://recharts.org/en-US/api/ResponsiveContainer

Actually, if I go to recharts.org, and I refresh the web page, I get 404 error. It looks all link is broken

**Comment by satsuya0114** [comment]
same issue~ 

It seems like router cannot run normally. 

Reload Page or Click URL directly ( except: http://recharts.org ) Will All get 404 Error
