### ISSUE TITLE
Treemap JSFiddle examples use 'ratio' prop

### ISSUE THREAD

**Issue by gknapp** [recharts/recharts.org#89]
I copied some code from your JSFiddle example (I'm using typescript). Typescript complains about the `ratio` prop. Although it works on JSFiddle, the prop documented in the API is `aspectRatio` not `ratio`.

Typescript would not compile until I updated my example code to use `aspectRatio`.

JSFiddle examples:
https://jsfiddle.net/alidingling/u702a3Lx/ (Simple)
https://jsfiddle.net/alidingling/Ldvvz2ak/ (Customised content)

Treemap API:
http://recharts.org/en-US/api/Treemap#aspectRatio

**Comment by ckifer** [comment]
yep this example needs updated, thanks!
